[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "colav-automaton"
version = "0.0.1"
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Ryan McKee", email = "ryanmckee47@icloud.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "shapely>=2.0",
  "numpy>=1.20",
  "scipy>=1.7",
  "colav-unsafe-set",
]

[project.urls]
Documentation = "https://github.com/Ryan McKee/colav-automaton#readme"
Issues = "https://github.com/Ryan McKee/colav-automaton/issues"
Source = "https://github.com/Ryan McKee/colav-automaton"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/colav_automaton src/colav_automaton_evaluation tests}"

[tool.coverage.run]
source_pkgs = ["colav_automaton", 'colav_automaton_evaluation', "tests"]
branch = true
parallel = true
omit = [
  "src/colav_automaton/__about__.py",
]

[tool.hatch.build.targets.wheel]
packages = ["src/colav_automaton", "src/colav_automaton_evaluation"]

[tool.coverage.paths]
colav_automaton = ["src/colav_automaton", "*/colav-automaton/src/colav_automaton"]
colav_autmoaton_evaluations = ["src/colav_automaton_evaluation", "*/colav-automaton/src/colav_automaton_evaluation"]
tests = ["tests", "*/colav-automaton/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
